name: Bot

on:
  pull_request:
    types: [ opened, ready_for_review, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  NODE_VERSION: 22.x

jobs:
  assign-reviewers:
    name: Assign reviewers
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm bot review assign \
            --owner ${{ github.repository_owner }} \
            --repo ${{ github.event.repository.name }} \
            --pull-number ${{ github.event.pull_request.number }}
