name: Bot

on:
  pull_request:
    types: [ opened, ready_for_review, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  NODE_VERSION: 22.x
  RUST_CHANNEL: stable

jobs:
  assign-reviewers:
    name: Assign reviewers
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          rust-channel: ${{ env.RUST_CHANNEL }}

      - name: Build libraries
        run: |
          ./crates/swc-plugin-jsx-marker/build.sh
          ./crates/swc-plugin-styled-components/build.sh

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm bot assign-reviewers \
            ${{ github.repository_owner }} \
            ${{ github.event.repository.name }} \
            ${{ github.event.pull_request.number }}
