name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - ".github/workflows/release.yml"
      - "crates/**"
      - "src/**"
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_VERSION: 22.x
  RUST_CHANNEL: stable

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          rust-channel: ${{ env.RUST_CHANNEL }}
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Setup pnpm with cache
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium

      - name: Test
        run: pnpm test

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Build design system
        run: pnpm build

      - name: Build libraries
        run: |
          (cd crates/swc-plugin-jsx-marker && ./build.sh)
          (cd crates/swc-plugin-styled-components && ./build.sh)
        shell: bash

      - name: Create release PR
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "Version packages"
          commitMode: github-api
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub releases
        if: steps.changesets.outputs.published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
        run: |
          echo "$PUBLISHED_PACKAGES" | jq -c '.[]' | while read package; do
            name=$(echo "$package" | jq -r '.name')
            version=$(echo "$package" | jq -r '.version')

            pnpm bot release \
              ${{ github.repository_owner }} \
              ${{ github.event.repository.name }} \
              "$name" \
              "$version"
          done
